name: LoveClaims
version: '1.5'
main: me.lovelace.loveclaims.LoveClaims
api-version: '1.21'
depend: [PlaceholderAPI]
softdepend: [CMI, LoveCore]
authors: [lovelace]
description: Advanced anchor-based claiming system.
commands:
  ac:
    description: Основная команда приватов
    aliases: [ claim, loveclaims, приват ]
  rental:
    description: Управление арендой
    aliases: [ rent ]
    permission: loveclaims.rental
  loveclaimsadmin:
    description: Административные команды LoveClaims (reload и т.д.)
    permission: loveclaims.admin
permissions:
  loveclaims.admin:
    description: Доступ к /loveclaimsadmin
    default: op
  loveclaims.bypass:
    description: Игнорирование защиты ВСЕХ приватов
    default: op
  loveclaims.moderator:
    description: Доступ к управлению любыми приватами (модерация)
    default: op
  loveclaims.rental:
    description: Базовый доступ к аренде (команда /rental)
    default: true
  loveclaims.rental.admin:
    description: Администрирование аренды
    default: op
  loveclaims.rental.bypasslimit:
    description: Обход лимита на количество арендуемых участков
    default: op
  loveclaims.bypass.expand:
    description: Расширение привата без ограничений по тиру
    default: op
  loveclaims.bypass.flags:
    description: Доступ ко всем флагам привата без открытия их через квесты
    default: op
