name: LoveClaims
version: '1.5'
main: me.lovelace.loveclaims.LoveClaims
api-version: '1.21'
depend: [PlaceholderAPI]
softdepend: [CMI]
authors: [lovelace]
description: Advanced anchor-based claiming system.
commands:
  ac:
    description: Основная команда приватов
    aliases: [ claim, loveclaims ]
  rental:
    description: Управление арендой
    aliases: [ rent ]
permissions:
  loveclaims.admin:
    description: Доступ к /ac admin
    default: op
  loveclaims.bypass:
    description: Игнорирование защиты ВСЕХ приватов
    default: op
  loveclaims.moderator:
    description: Доступ к управлению любыми приватами (модерация)
    default: op
  loveclaims.rental:
    description: Базовый доступ к аренде
    default: true
  loveclaims.rental.admin:
    description: Администрирование аренды
    default: op
  loveclaims.rental.taxcollector:
    description: Доступ к налоговому сборщику
    default: true
  loveclaims.expand:
    default: false
  loveclaims.flag.pvp:
    default: false
  loveclaims.flag.msg:
    default: false
  loveclaims.flag.hide:
    default: false
  loveclaims.flag.deny:
    default: false
  loveclaims.flag.enderpearl:
    default: false
  loveclaims.flag.chorus:
    default: false
  loveclaims.flag.elytra:
    default: false
  loveclaims.flag.interact:
    default: false
  loveclaims.flag.haste:
    default: false
  loveclaims.flag.regen:
    default: false
  loveclaims.flag.saturation:
    default: false
  loveclaims.flag.crop_growth:
    default: false
